version: '3'

services:
  frontapp:
    build: ./FrontEnd
    image: ${DOCKER_USR}/frontapp
    ports:
      - "8082:8080"

  backapp:
    build: ./BackEnd
    image: ${DOCKER_USR}/backapp
    ports:
      - "8081:8080"
